Revert back to jsdom 5.6.0
jsdom 6.x.x (tried all of them) keeps generating errors (tested in iojs-v2.5.0 - iojs v3.2.0):

```log
home/travis/build/sverweij/mscgen_js/node_modules/jsdom/lib/jsdom/browser/resource-loader.js:12
  var baseElements = document.getElementsByTagName("base");
                               ^
TypeError: Cannot read property 'getElementsByTagName' of undefined
    at getDocumentBaseUrl
(/home/travis/build/sverweij/mscgen_js/node_modules/jsdom/lib/jsdom/browser/resource-loader.js:12:30)

(...)

(/home/travis/build/sverweij/mscgen_js/node_modules/istanbul/lib/hook.js:109:37)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous>
(/home/travis/build/sverweij/mscgen_js/src/script/test/t_renderast.js:4:13)
    at Module._compile (module.js:430:26)
    at Object.Module._extensions..js (module.js:448:10)
    at Object.Module._extensions.(anonymous function) [as .js]

```

t_renderast.js:4:13 is the r of require:
```javascript
var jsdom = require("jsdom");
```